---
title: "imputation"
author: "Kristian Edosomwan"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries

```{r}
library(tidyverse)
library(mice)
library(howManyImputations)
library(gtsummary)
library(survey)
library(mitools)
```

# Load Dataset
```{r}
df_stata <- haven::read_dta("gcq_hsls_subset.dta")
```

# Modify Dataset
```{r}
## Binary should be be 0/1 factor for logreg
df <- df_stata %>% mutate(
  first_gen = factor(first_gen, levels = c(0,1)),
  exp_ba = factor(exp_ba, levels = c(0,1)),
  frpl = factor(frpl, levels = c(0,1)),
  p1honors = factor(p1honors, levels = c(0,1))
) 

# Ordinal must be ordered factors
df$math_4level <- ordered(df$math_4level)
df$par_exp     <- ordered(df$par_exp)
df$pov_level <- ordered(df$pov_level)
df$math_quintile <- ordered(df$math_quintile)

# nominal must be factors
df$stud_race <- factor(df$stud_race)
df$par_race <- factor(df$par_race)
df$first_lang <- factor(df$first_lang)

df_subset <- df %>% dplyr::select(stu_id, p1honors, par_exp, math_4level, par_sch_inv, female, par_ba, first_lang, frpl, math_score, public, x1locale, stud_race, starts_with("w1"))
colSums(is.na(df_subset))
```

# Initial Run and Methods

```{r}
#Dry run: iterations = 0
init <- mice(df_subset, maxit = 0)
meth <- init$method
meth
```


```{r}
# Run chained equations imputation
df_imp <- mice(
  df_subset,
  m        = 20,     
  seed     = 123
)

# Save the imputed data
save(df_imp, file = "df_imputed.rdata")

# Load imputed data
#load("df_imputed.rdata")
```

## Racial/Ethnic Subgroups

### Write function
```{r}

run_hsls_glm <- function(data) {
  with(data,   glm(
    p1honors ~ math_3level + 
      par_exp + par_sch_inv +
      first_gen + first_lang + frpl +
      math_score + public + urban,
    family = "binomial"
  ))
}
hsls_tbl_merge <- function(data){
  data %>% 
    tbl_regression(exp = TRUE) %>% 
    add_significance_stars(hide_se = FALSE, hide_p = TRUE, hide_ci = TRUE) %>% 
    add_glance_source_note() 
}
hsls_tbl_view <- function(data){
  data %>% 
    tbl_regression(exp = TRUE) %>% 
    add_significance_stars(hide_se = FALSE, hide_p = FALSE, hide_ci = FALSE) %>% 
    add_glance_table() %>% 
    as_flex_table()
}

```

## Asian American
```{r}
asian_imp <- filter(df_imp, stud_race == 1)
asian_glm <- run_hsls_glm(asian_imp)
asian_glm %>% hsls_tbl_view()
asian_tbl <- asian_glm %>% hsls_tbl_merge
how_many_imputations(asian_glm)
```

## Black
```{r}
# Create Black subset
black_imp <- filter(df_imp, stud_race == 2)

# Run Imputation & check how many needed
black_glm <- black_imp %>% run_hsls_glm()
black_glm %>% how_many_imputations()

# Create Tables
black_tbl <- black_glm %>% hsls_tbl_merge
black_glm %>% hsls_tbl_view()
```

## Indigenous
```{r}
indigenous_imp <- filter(df_imp, stud_race == 3)

# Run Imputation & check how many needed
indigenous_glm <- indigenous_imp %>% run_hsls_glm()
indigenous_glm %>% how_many_imputations()

# Create Tables
indigenous_tbl <- indigenous_glm %>% hsls_tbl_merge
indigenous_glm %>% hsls_tbl_view()
```

## Latinx
```{r}
latinx_imp <- filter(df_imp, stud_race == 4)

# Run Imputation & check how many needed
latinx_glm <- latinx_imp %>% run_hsls_glm()
latinx_glm %>% how_many_imputations()

# Create Tables
latinx_tbl <- latinx_glm %>% hsls_tbl_merge
latinx_glm %>% hsls_tbl_view()
```

## Two or More Races
```{r}
multi_imp <- filter(df_imp, stud_race == 5)

# Run Imputation & check how many needed
multi_glm <- multi_imp %>% run_hsls_glm()
multi_glm %>% how_many_imputations()

# Create Tables
multi_tbl <- multi_glm %>% hsls_tbl_merge
multi_glm %>% hsls_tbl_view()
```

## White
```{r}
white_imp <- filter(df_imp, stud_race == 6)

# Run Imputation & check how many needed
white_glm <- white_imp %>% run_hsls_glm()
white_glm %>% how_many_imputations()

# Create Tables
white_tbl <- white_glm %>% hsls_tbl_merge
white_glm %>% hsls_tbl_view()
```
